import React, { useMemo, useRef, useState } from "react";
import { useFrame } from "@react-three/fiber";
import * as THREE from "three";
import { Html } from "@react-three/drei";

interface AircraftProps {
  mode: "hologram" | "cfd";
  angleOfAttack: number;
}

const AERO_DETAILS: Record<string, string> = {
  "Lift Force":
    "The mechanical force generated by the interaction of the airplane moving through the air, acting perpendicular to the relative wind.",
  Drag: "Aerodynamic resistance force acting opposite to the relative motion of the aircraft through the fluid.",
  Thrust:
    "The propulsive force produced by the engines to overcome drag and accelerate the aircraft.",
  Weight:
    "The gravitational force acting downwards, equal to the mass of the aircraft multiplied by the acceleration due to gravity.",
  Fuselage:
    "The main body of the aircraft, which houses the cockpit, crew, and payload, designed as a streamlined aerodynamic shell.",
  "Nose Cone":
    "The forwardmost section of the fuselage, shaped to minimize drag and house radar or sensor equipment.",
  "Cockpit Canopy":
    "The transparent enclosure over the cockpit, providing visibility while maintaining structural integrity and aerodynamics.",
  "Air Intakes":
    "Precision-engineered openings that channel airflow to the jet engines for combustion and cooling.",
  Afterburners:
    "Reheat systems that inject fuel into the exhaust stream to provide additional thrust for supersonic flight.",
  "Main Delta Wing":
    "The primary lifting surface, utilizing a triangular shape for high-speed stability and structural efficiency.",
  Canards:
    "Small forward winglets used for pitch control and to improve airflow over the main wings at high angles of attack.",
  "Vertical Stabilizer":
    "The vertical tail surface providing directional stability and housing the rudder for yaw control.",
};

function SmartHtml({
  children,
  name,
  description,
  color = "#00ffff",
  ...props
}: any) {
  const [hovered, setHovered] = useState(false);
  const textContent = typeof children === "string" ? children : "";
  const labelName = name || textContent;
  const labelDesc =
    description ||
    AERO_DETAILS[labelName] ||
    "Detailed aeronautical specification for the current aircraft module.";

  return (
    <Html {...props} zIndexRange={[100, 0]}>
      <div
        className="relative flex flex-col items-center"
        onPointerEnter={(e) => {
          e.stopPropagation();
          setHovered(true);
        }}
        onPointerLeave={() => setHovered(false)}
      >
        {children(hovered)}
        {hovered && (
          <div className="absolute top-full mt-2 left-1/2 -translate-x-1/2 bg-zinc-900/95 border border-white/10 text-white p-3 rounded-xl text-[10px] pointer-events-none whitespace-normal w-48 shadow-2xl z-50 backdrop-blur-md">
            <div className="flex flex-col gap-1">
              <strong
                className="uppercase tracking-widest text-[8px] mb-1"
                style={{ color }}
              >
                Aeronautical Data
              </strong>
              <span className="font-bold text-white text-xs">{labelName}</span>
              <p className="text-zinc-400 leading-relaxed font-medium">
                {labelDesc}
              </p>
            </div>
          </div>
        )}
      </div>
    </Html>
  );
}

function VectorArrow({
  direction,
  length,
  color,
  label,
}: {
  direction: [number, number, number];
  length: number;
  color: string;
  label: string;
}) {
  const arrowRef = useRef<THREE.Group>(null);

  return (
    <group ref={arrowRef}>
      {/* Arrow Shaft */}
      <mesh
        position={[
          (direction[0] * length) / 2,
          (direction[1] * length) / 2,
          (direction[2] * length) / 2,
        ]}
      >
        <boxGeometry
          args={[
            direction[0] !== 0 ? length : 0.03,
            direction[1] !== 0 ? length : 0.03,
            direction[2] !== 0 ? length : 0.03,
          ]}
        />
        <meshBasicMaterial color={color} transparent opacity={0.8} />
      </mesh>
      {/* Arrow Head */}
      <mesh
        position={[
          direction[0] * length,
          direction[1] * length,
          direction[2] * length,
        ]}
        rotation={[
          direction[1] !== 0
            ? direction[1] > 0
              ? 0
              : Math.PI
            : direction[0] > 0
              ? -Math.PI / 2
              : Math.PI / 2,
          0,
          0,
        ]}
      >
        <coneGeometry args={[0.1, 0.2, 8]} />
        <meshBasicMaterial color={color} transparent opacity={0.8} />
      </mesh>
      {/* Label */}
      <SmartHtml
        position={[
          direction[0] * length * 1.2,
          direction[1] * length * 1.2,
          direction[2] * length * 1.2,
        ]}
        center
        color={color}
        name={label}
      >
        {(hovered: boolean) => (
          <div className="flex flex-col items-center">
            {/* Simple interaction handle */}
            <div
              className={`w-3 h-3 rounded-full cursor-help transition-all duration-300 ${hovered ? "scale-150" : "opacity-80"}`}
              style={{
                backgroundColor: color,
                boxShadow: hovered ? `0 0 10px ${color}` : "none",
              }}
            ></div>

            {/* The Text tag - only on hover */}
            {hovered && (
              <div className="absolute top-4 px-2 py-0.5 bg-black/80 backdrop-blur-md border border-white/10 rounded cursor-help z-50 whitespace-nowrap mt-1 pointer-events-none">
                <span
                  className="text-[8px] font-bold uppercase tracking-widest whitespace-nowrap"
                  style={{ color }}
                >
                  {label}
                </span>
              </div>
            )}
          </div>
        )}
      </SmartHtml>
    </group>
  );
}

function PartLabel({
  position,
  label,
}: {
  position: [number, number, number];
  label: string;
}) {
  const [hovered, setHovered] = useState(false);
  const labelDesc =
    AERO_DETAILS[label] ||
    "Detailed aeronautical specification for the current aircraft module.";

  return (
    <Html position={position} center distanceFactor={10} zIndexRange={[100, 0]}>
      <div
        className="flex flex-col items-center group cursor-help relative"
        onPointerEnter={(e) => {
          e.stopPropagation();
          setHovered(true);
        }}
        onPointerLeave={() => setHovered(false)}
      >
        <div
          className={`w-2 h-2 rounded-full transition-all duration-300 ${hovered ? "bg-cyan-400 scale-150 shadow-[0_0_10px_rgba(34,211,238,0.8)]" : "bg-white/40 border border-white/20"}`}
        />

        {hovered && (
          <div className="absolute top-4 left-1/2 -translate-x-1/2 mt-2 flex flex-col items-center pointer-events-none z-50">
            <div className="mb-1 px-2 py-0.5 bg-zinc-900/90 backdrop-blur-md border border-white/20 rounded shadow-xl">
              <span className="text-[10px] text-white font-bold uppercase tracking-widest whitespace-nowrap">
                {label}
              </span>
            </div>
            <div className="bg-zinc-900/95 border border-white/10 text-white p-3 rounded-xl text-[10px] whitespace-normal w-48 shadow-2xl backdrop-blur-md">
              <div className="flex flex-col gap-1">
                <strong className="uppercase tracking-widest text-[8px] mb-1 text-cyan-400">
                  Aeronautical Data
                </strong>
                <p className="text-zinc-400 leading-relaxed font-medium">
                  {labelDesc}
                </p>
              </div>
            </div>
          </div>
        )}
      </div>
    </Html>
  );
}

export function Aircraft({ mode, angleOfAttack }: AircraftProps) {
  const groupRef = useRef<THREE.Group>(null);
  const aoaRad = (angleOfAttack * Math.PI) / 180;

  // Aerodynamic coefficients calculation for vector scaling
  const liftCoeff = Math.sin(aoaRad) * 4 + 0.5;
  const dragCoeff = Math.abs(Math.sin(aoaRad)) * 2 + 0.2;

  // Hologram Material (Cyan Wireframe)
  const holoMaterial = useMemo(
    () =>
      new THREE.MeshStandardMaterial({
        color: "#00ffff",
        emissive: "#00ffff",
        emissiveIntensity: 0.8,
        wireframe: true,
        transparent: true,
        opacity: 0.6,
      }),
    [],
  );

  // CFD Solid Material (Sleek Metallic)
  const solidMaterial = useMemo(
    () =>
      new THREE.MeshStandardMaterial({
        color: "#a0b0c0",
        metalness: 0.9,
        roughness: 0.2,
        envMapIntensity: 1,
      }),
    [],
  );

  const material = mode === "hologram" ? holoMaterial : solidMaterial;

  // Custom Shapes for Wings and Tail
  const deltaWingShape = useMemo(() => {
    const shape = new THREE.Shape();
    shape.moveTo(0.5, 0); // Root front
    shape.lineTo(-2.5, 0); // Root back
    shape.lineTo(-2.5, 2.2); // Wingtip back
    shape.lineTo(-1.0, 2.2); // Wingtip front
    shape.lineTo(0.5, 0); // Back to root
    return shape;
  }, []);

  const canardShape = useMemo(() => {
    const shape = new THREE.Shape();
    shape.moveTo(1.5, 0);
    shape.lineTo(0.5, 0);
    shape.lineTo(0.5, 0.8);
    shape.lineTo(1.0, 0.8);
    shape.lineTo(1.5, 0);
    return shape;
  }, []);

  const tailShape = useMemo(() => {
    const shape = new THREE.Shape();
    shape.moveTo(-1.0, 0);
    shape.lineTo(-2.5, 0);
    shape.lineTo(-2.8, 1.5);
    shape.lineTo(-1.8, 1.5);
    shape.lineTo(-1.0, 0);
    return shape;
  }, []);

  const extrudeSettings = {
    depth: 0.05,
    bevelEnabled: true,
    bevelSegments: 2,
    steps: 1,
    bevelSize: 0.02,
    bevelThickness: 0.02,
  };

  // Gentle hover animation + AoA rotation
  useFrame((state) => {
    if (groupRef.current) {
      groupRef.current.position.y =
        Math.sin(state.clock.elapsedTime * 2) * 0.05;

      // Base rotation from AoA (pitch)
      const pitch = -aoaRad;

      if (mode === "hologram") {
        groupRef.current.rotation.z =
          pitch + Math.sin(state.clock.elapsedTime * 0.5) * 0.02;
        groupRef.current.rotation.x =
          Math.sin(state.clock.elapsedTime * 0.3) * 0.01;
      } else {
        groupRef.current.rotation.z = pitch;
        groupRef.current.rotation.x = 0;
      }
    }
  });

  return (
    <group ref={groupRef} scale={1.2}>
      {/* Aerodynamic Force Vectors */}
      {mode === "hologram" && (
        <group position={[0, 0, 0]}>
          <VectorArrow
            direction={[0, 1, 0]}
            length={liftCoeff}
            color="#22d3ee"
            label="Lift Force"
          />
          <VectorArrow
            direction={[-1, 0, 0]}
            length={dragCoeff}
            color="#f43f5e"
            label="Drag"
          />
          <VectorArrow
            direction={[1, 0, 0]}
            length={2.5}
            color="#fbbf24"
            label="Thrust"
          />
          <VectorArrow
            direction={[0, -1, 0]}
            length={1.5}
            color="#ffffff"
            label="Weight"
          />
        </group>
      )}

      {/* Main Fuselage */}
      <mesh
        material={material}
        position={[0, 0, 0]}
        rotation={[0, 0, Math.PI / 2]}
      >
        <capsuleGeometry args={[0.35, 4, 16, 32]} />
      </mesh>
      <PartLabel position={[0, 0.5, 0]} label="Fuselage" />

      {/* Nose Cone */}
      <mesh
        material={material}
        position={[2.5, 0, 0]}
        rotation={[0, 0, -Math.PI / 2]}
      >
        <coneGeometry args={[0.35, 1.5, 32]} />
      </mesh>
      <PartLabel position={[3, 0, 0]} label="Nose Cone" />

      {/* Canopy */}
      <mesh
        material={material}
        position={[1.0, 0.25, 0]}
        scale={[1.5, 0.5, 0.4]}
      >
        <sphereGeometry args={[0.5, 32, 16]} />
      </mesh>
      <PartLabel position={[1.2, 0.6, 0]} label="Cockpit Canopy" />

      {/* Engine Intakes */}
      <mesh
        material={material}
        position={[0.5, -0.1, 0.4]}
        rotation={[0, 0, 0]}
      >
        <boxGeometry args={[1.5, 0.4, 0.3]} />
      </mesh>
      <mesh
        material={material}
        position={[0.5, -0.1, -0.4]}
        rotation={[0, 0, 0]}
      >
        <boxGeometry args={[1.5, 0.4, 0.3]} />
      </mesh>
      <PartLabel position={[0.5, -0.5, 0.5]} label="Air Intakes" />

      {/* Engine Exhausts */}
      <mesh
        material={material}
        position={[-2.2, 0, 0.25]}
        rotation={[0, 0, Math.PI / 2]}
      >
        <cylinderGeometry args={[0.25, 0.3, 0.8, 16]} />
      </mesh>
      <mesh
        material={material}
        position={[-2.2, 0, -0.25]}
        rotation={[0, 0, Math.PI / 2]}
      >
        <cylinderGeometry args={[0.25, 0.3, 0.8, 16]} />
      </mesh>
      <PartLabel position={[-2.5, 0, 0.5]} label="Afterburners" />

      {/* Right Wing */}
      <mesh
        material={material}
        position={[0, 0, 0.3]}
        rotation={[Math.PI / 2, 0, 0]}
      >
        <extrudeGeometry args={[deltaWingShape, extrudeSettings]} />
      </mesh>

      {/* Left Wing */}
      <mesh
        material={material}
        position={[0, 0, -0.3]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <extrudeGeometry args={[deltaWingShape, extrudeSettings]} />
      </mesh>
      <PartLabel position={[-1, 0, 1.5]} label="Main Delta Wing" />

      {/* Right Canard */}
      <mesh
        material={material}
        position={[0, 0.1, 0.25]}
        rotation={[Math.PI / 2, 0, 0]}
      >
        <extrudeGeometry args={[canardShape, extrudeSettings]} />
      </mesh>

      {/* Left Canard */}
      <mesh
        material={material}
        position={[0, 0.1, -0.25]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <extrudeGeometry args={[canardShape, extrudeSettings]} />
      </mesh>
      <PartLabel position={[1, 0.2, 0.5]} label="Canards" />

      {/* Vertical Tail */}
      <mesh material={material} position={[0, 0.3, 0]} rotation={[0, 0, 0]}>
        <extrudeGeometry args={[tailShape, extrudeSettings]} />
      </mesh>
      <PartLabel position={[-2, 1.2, 0]} label="Vertical Stabilizer" />

      {/* Drop Tanks (Under wings) */}
      <mesh
        material={material}
        position={[-0.5, -0.3, 1.2]}
        rotation={[0, 0, Math.PI / 2]}
      >
        <capsuleGeometry args={[0.15, 1.5, 16, 16]} />
      </mesh>
      <mesh
        material={material}
        position={[-0.5, -0.3, -1.2]}
        rotation={[0, 0, Math.PI / 2]}
      >
        <capsuleGeometry args={[0.15, 1.5, 16, 16]} />
      </mesh>

      {/* Wingtip Missiles */}
      <mesh
        material={material}
        position={[-1.5, 0, 2.3]}
        rotation={[0, 0, Math.PI / 2]}
      >
        <cylinderGeometry args={[0.05, 0.05, 1.2, 8]} />
      </mesh>
      <mesh
        material={material}
        position={[-1.5, 0, -2.3]}
        rotation={[0, 0, Math.PI / 2]}
      >
        <cylinderGeometry args={[0.05, 0.05, 1.2, 8]} />
      </mesh>
    </group>
  );
}
